project:
  type: website
  output-dir: docs

website:
  title: "Статистика, R и социология"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AlexRforScience
      - icon: telegram
        href: https://t.me/Cyber_marginal_671
format:
  html:
    theme:
      light: default
      dark: darkly
    css: styles.css

editor: visual

